### ISSUE TITLE
Pull Request作ってみてください

### ISSUE THREAD

**Issue by abgata20000** [RintaroTawara/kinniku#18]
招待ありがとうございます。

なんだもいいので一度入れて変更みてpull request作ってみてください

reviewerにabgata20000設定して、念の為メンション付きでコメントもらえると気づきやすいです

よろしくおねがいします。

**Comment by abgata20000** [comment]
@RintaroTawara メンション

**Comment by abgata20000** [comment]
@RintaroTawara 何でもいいというのも難しいと思ったので、githubテンプレートでも追加しましょうか
refs: https://qiita.com/nyamogera/items/3fe6985b45fbd5377184

issue用とpr用とそれぞれ追加してみてください
内容に迷うのであれば、自分がよく設定するものを貼っておくので参考にでもしてください。

- issue
```
<!-- バグ改修のテンプレート -->
### 概要・事象 <!-- 対象URL、頻度など具体的に -->
### 関連issue <!-- あれば -->
### 再現手順 <!-- 明確に -->
### 解決の定義 <!-- どうなることが解決なのか、正解とするのか -->

<!-- 機能追加希望のテンプレート -->
### 経緯・目的 <!-- 具体的に -->
### 関連issue <!-- あれば -->
### 概要・提案 <!-- 対象URLなど、対応方法の仮定、明確に -->
### 解決の定義 <!-- どうなることが正解とするのか -->

```

- pr
```
### 概要
<!-- 変更の目的 もしくは 関連する Issue 番号 -->

### 変更内容
<!-- ビューの変更がある場合はスクショによる比較などがあるとわかりやすい -->

### 予定時間 / 実績時間

### 影響範囲
<!-- この関数を変更したのでこの機能にも影響がある、など -->

### 動作要件
<!-- 動作に必要な 環境変数 / 依存関係 / DBの更新 など -->

### 動作確認方法
<!-- 動作した手順や動作確認してほしい手順等を記載 -->

### 補足
<!-- レビューをする際に見てほしい点、ローカル環境で試す際の注意点、など -->

```

**Comment by RintaroTawara** [comment]
@abgata20000 
GitHubテンプレートを追加し、prさせて頂きました。
内容は提案いただいたテンプレートをそのまま使わせて頂きました。
このテンプレートを使用していき、随時自分の設定に変更していきたいと思います。ご確認の程よろしくお願い致します。

**Comment by abgata20000** [comment]
マージされたので閉じる
